### ISSUE TITLE
Yeoman Generation overwrite files

### ISSUE THREAD

**Issue by jbrodley** [rothgar/docker-hubot#1]
When I attempted to use this, it works correctly, but at docker run time as it doesn't have Hubot already generated, it attempts to run Yeoman, it than has an interactive prompt to overwrite the external-scripts, package.json, etc. 

I assume your build may already have these files in place?

**Comment by purplefish32** [comment]
This is still an issue for me

**Comment by JigSawFr** [comment]
Need to use `--force` option when running yeoman to force overwriting files
